In [1]:
import sys
print(sys.executable)

C:\Users\Imraan\anaconda3\envs\data-analytics\python.exe

In [2]:
import pandas
import sqlalchemy

In [3]:
print("Pandas: ", pandas.__version__)
print("SQLAlchemy:", sqlalchemy.__version__)

Pandas:  3.0.6
SQLAlchemy: 2.1.1

In [4]:
%pip install kaggle pyodbc

Collecting kaggle
  Downloading kaggle-2.2.4-py3-none-any.whl.metadata (17 kB)
Collecting pyodbc
  Downloading pyodbc-5.3.0-cp312-cp312-win_amd64.whl.metadata (2.8 kB)
Collecting bleach (from kaggle)
  Downloading bleach-6.4.0-py3-none-any.whl.metadata (32 kB)
Collecting jupytext (from kaggle)
  Downloading jupytext-1.19.5-py3-none-any.whl.metadata (15 kB)
Collecting kagglesdk<1.0,>=0.1.35 (from kaggle)
  Downloading kagglesdk-0.1.37-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in C:\Users\Imraan\anaconda3\envs\data-analytics\Lib\site-packages (from kaggle) (26.3)
Collecting protobuf (from kaggle)
  Downloading protobuf-7.36.2-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: python-dateutil in C:\Users\Imraan\anaconda3\envs\data-analytics\Lib\site-packages (from kaggle) (2.9.0.post0)
Collecting python-dotenv (from kaggle)
  Downloading python_dotenv-1.2.3-py3-none-any.whl.metadata (29 kB)
Collecting python-slugify (from kaggle)
  Downloading python_slugify-9.1.1-py3-none-any.whl.metadata (12 kB)
Collecting requests (from kaggle)
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting tqdm (from kaggle)
  Downloading tqdm-4.70.1-py3-none-any.whl.metadata (57 kB)
Collecting urllib3>=1.15.1 (from kaggle)
  Downloading urllib3-2.8.0-py3-none-any.whl.metadata (7.4 kB)
Collecting webencodings (from bleach->kaggle)
  Downloading webencodings-0.6.1-py3-none-any.whl.metadata (3.4 kB)
Collecting markdown-it-py>=1.0 (from jupytext->kaggle)
  Downloading markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Collecting mdit-py-plugins (from jupytext->kaggle)
  Downloading mdit_py_plugins-0.6.1-py3-none-any.whl.metadata (2.9 kB)
Collecting nbformat (from jupytext->kaggle)
  Downloading nbformat-5.11.1-py3-none-any.whl.metadata (3.7 kB)
Collecting pyyaml (from jupytext->kaggle)
  Downloading pyyaml-6.0.3-cp312-cp312-win_amd64.whl.metadata (2.4 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=1.0->jupytext->kaggle)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Collecting fastjsonschema>=2.15 (from nbformat->jupytext->kaggle)
  Downloading fastjsonschema-2.22.2-py3-none-any.whl.metadata (2.1 kB)
Collecting jsonschema>=2.6 (from nbformat->jupytext->kaggle)
  Using cached jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in C:\Users\Imraan\anaconda3\envs\data-analytics\Lib\site-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in C:\Users\Imraan\anaconda3\envs\data-analytics\Lib\site-packages (from nbformat->jupytext->kaggle) (5.16.1)
Collecting attrs>=22.2.0 (from jsonschema>=2.6->nbformat->jupytext->kaggle)
  Using cached attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=2.6->nbformat->jupytext->kaggle)
  Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=2.6->nbformat->jupytext->kaggle)
  Using cached referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=2.6->nbformat->jupytext->kaggle)
  Downloading rpds_py-2026.6.3-cp312-cp312-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: platformdirs>=2.5 in C:\Users\Imraan\anaconda3\envs\data-analytics\Lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.12.0)
Requirement already satisfied: typing-extensions>=4.4.0 in C:\Users\Imraan\anaconda3\envs\data-analytics\Lib\site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.16.0)
Requirement already satisfied: six>=1.5 in C:\Users\Imraan\anaconda3\envs\data-analytics\Lib\site-packages (from python-dateutil->kaggle) (1.17.0)
Collecting text-unidecode>=1.3 (from python-slugify->kaggle)
  Downloading text_unidecode-1.3-py2.py3-none-any.whl.metadata (2.4 kB)
Collecting charset_normalizer<4,>=2 (from requests->kaggle)
  Downloading charset_normalizer-3.5.1-cp312-cp312-win_amd64.whl.metadata (46 kB)
Collecting idna<4,>=2.5 (from requests->kaggle)
  Downloading idna-3.20-py3-none-any.whl.metadata (7.2 kB)
Collecting certifi>=2023.5.7 (from requests->kaggle)
  Downloading certifi-2026.7.22-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: colorama in C:\Users\Imraan\anaconda3\envs\data-analytics\Lib\site-packages (from tqdm->kaggle) (0.4.6)
Downloading kaggle-2.2.4-py3-none-any.whl (126 kB)
Downloading kagglesdk-0.1.37-py3-none-any.whl (262 kB)
Downloading pyodbc-5.3.0-cp312-cp312-win_amd64.whl (70 kB)
Downloading urllib3-2.8.0-py3-none-any.whl (135 kB)
Downloading bleach-6.4.0-py3-none-any.whl (165 kB)
Downloading jupytext-1.19.5-py3-none-any.whl (229 kB)
Downloading markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Downloading mdit_py_plugins-0.6.1-py3-none-any.whl (66 kB)
Downloading nbformat-5.11.1-py3-none-any.whl (79 kB)
Downloading fastjsonschema-2.22.2-py3-none-any.whl (27 kB)
Using cached jsonschema-4.26.0-py3-none-any.whl (90 kB)
Using cached attrs-26.1.0-py3-none-any.whl (67 kB)
Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Using cached referencing-0.37.0-py3-none-any.whl (26 kB)
Downloading rpds_py-2026.6.3-cp312-cp312-win_amd64.whl (220 kB)
Downloading protobuf-7.36.2-cp310-abi3-win_amd64.whl (456 kB)
Downloading python_dotenv-1.2.3-py3-none-any.whl (22 kB)
Downloading python_slugify-9.1.1-py3-none-any.whl (15 kB)
Downloading text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
Downloading pyyaml-6.0.3-cp312-cp312-win_amd64.whl (154 kB)
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
Downloading charset_normalizer-3.5.1-cp312-cp312-win_amd64.whl (200 kB)
Downloading idna-3.20-py3-none-any.whl (69 kB)
Downloading certifi-2026.7.22-py3-none-any.whl (136 kB)
Downloading tqdm-4.70.1-py3-none-any.whl (80 kB)
Downloading webencodings-0.6.1-py3-none-any.whl (8.7 kB)
Installing collected packages: text-unidecode, webencodings, urllib3, tqdm, rpds-py, pyyaml, python-slugify, python-dotenv, pyodbc, protobuf, mdurl, idna, fastjsonschema, charset_normalizer, certifi, attrs, requests, referencing, markdown-it-py, bleach, mdit-py-plugins, kagglesdk, jsonschema-specifications, jsonschema, nbformat, jupytext, kaggle

   -- -------------------------------------  2/27 [urllib3]
   ---- -----------------------------------  3/27 [tqdm]
   ---- -----------------------------------  3/27 [tqdm]
   ------- --------------------------------  5/27 [pyyaml]
   ---------- -----------------------------  7/27 [python-dotenv]
   ------------- --------------------------  9/27 [protobuf]
   ------------- --------------------------  9/27 [protobuf]
   ------------- --------------------------  9/27 [protobuf]
   ---------------- ----------------------- 11/27 [idna]
   ----------------- ---------------------- 12/27 [fastjsonschema]
   ----------------- ---------------------- 12/27 [fastjsonschema]
   ------------------- -------------------- 13/27 [charset_normalizer]
   ---------------------- ----------------- 15/27 [attrs]
   ---------------------- ----------------- 15/27 [attrs]
   ----------------------- ---------------- 16/27 [requests]
   ------------------------- -------------- 17/27 [referencing]
   -------------------------- ------------- 18/27 [markdown-it-py]
   -------------------------- ------------- 18/27 [markdown-it-py]
   ---------------------------- ----------- 19/27 [bleach]
   ---------------------------- ----------- 19/27 [bleach]
   ---------------------------- ----------- 19/27 [bleach]
   ----------------------------- ---------- 20/27 [mdit-py-plugins]
   ------------------------------- -------- 21/27 [kagglesdk]
   ------------------------------- -------- 21/27 [kagglesdk]
   ------------------------------- -------- 21/27 [kagglesdk]
   ------------------------------- -------- 21/27 [kagglesdk]
   ------------------------------- -------- 21/27 [kagglesdk]
   ------------------------------- -------- 21/27 [kagglesdk]
   ------------------------------- -------- 21/27 [kagglesdk]
   ------------------------------- -------- 21/27 [kagglesdk]
   ---------------------------------- ----- 23/27 [jsonschema]
   ---------------------------------- ----- 23/27 [jsonschema]
   ---------------------------------- ----- 23/27 [jsonschema]
   ----------------------------------- ---- 24/27 [nbformat]
   ----------------------------------- ---- 24/27 [nbformat]
   ------------------------------------- -- 25/27 [jupytext]
   ------------------------------------- -- 25/27 [jupytext]
   ------------------------------------- -- 25/27 [jupytext]
   -------------------------------------- - 26/27 [kaggle]
   ---------------------------------------- 27/27 [kaggle]

Successfully installed attrs-26.1.0 bleach-6.4.0 certifi-2026.7.22 charset_normalizer-3.5.1 fastjsonschema-2.22.2 idna-3.20 jsonschema-4.26.0 jsonschema-specifications-2025.9.1 jupytext-1.19.5 kaggle-2.2.4 kagglesdk-0.1.37 markdown-it-py-4.2.0 mdit-py-plugins-0.6.1 mdurl-0.1.2 nbformat-5.11.1 protobuf-7.36.2 pyodbc-5.3.0 python-dotenv-1.2.3 python-slugify-9.1.1 pyyaml-6.0.3 referencing-0.37.0 requests-2.34.2 rpds-py-2026.6.3 text-unidecode-1.3 tqdm-4.70.1 urllib3-2.8.0 webencodings-0.6.1
Note: you may need to restart the kernel to use updated packages.

In [5]:
import kaggle
import pyodbc

print("Kaggle: OK")
print("PyODBC: OK")

Authentication required to call the Kaggle API.

First, you will need a Kaggle account. You can sign up at
  https://www.kaggle.com/account/login

Recommended: log in with OAuth via a web-based authorization flow.
No token to manage; credentials are cached locally for you.
    kaggle auth login

If you'd rather not use OAuth, generate an API token at
  https://www.kaggle.com/settings/api  (click "Generate New Token" under "API")
and supply it to the CLI in one of these ways:

  Option A: Environment variable
    export KAGGLE_API_TOKEN=xxxxxxxxxxxxxx  # token copied from the settings UI

  Option B: API token file
    Save the token to ~/.kaggle/access_token
Kaggle: OK
PyODBC: OK

In [6]:
!kaggle auth login

Your browser has been opened to visit:
  https://www.kaggle.com/api/v1/oauth2/authorize?response_type=code&client_id=kagglesdk&redirect_uri=http%3A%2F%2Flocalhost%3A8909&scope=resources.admin%3A%2A&state=8526d2ff-e40a-487d-83a2-bdb56b52fe0a&code_challenge=1SQBURVHuMrfqu2jcaMVI1V8NsfnirOnW0aClXnAVWU%3D&code_challenge_method=S256&response_mode=query



You are now logged in as [minhazulislam1999]

127.0.0.1 - - [27/Sep/2026 16:03:20] "GET /?code=CfDJ8LXGgraiXMNClPzcySXY5U6-rL8si1fRGbRRDKrKNl422x4KGFQx9dqXJc_zCeRysdQvCyXR3h0K-CHrVhaaTArr8iC4MfsctQhKQwzHytBe8ZITP9Wqhmi27MkG4-R7dscWDYpMWwA3DUa7h3Bn8saToc6UOSyZtrkTCqNo6qNk1EIbfk33g2fK7AS1vu0HHEswFWkDVvNEV_kV2xaWxawp0UA-mFreSnpdERUaC_pHH8dRAlByu1EgXGEOVeiUba67e1qKt6WuT2TCOHQmCSkofaaPNfv09VmC9pH7M1VYuabd2Vvc8W2SBgY3&state=8526d2ff-e40a-487d-83a2-bdb56b52fe0a HTTP/1.1" 200 -

In [7]:
!kaggle datasets list -s retail-orders

ref                                                   title                                                     size  lastUpdated                 downloadCount  voteCount  usabilityRating
----------------------------------------------------  --------------------------------------------------  ----------  --------------------------  -------------  ---------  ---------------
gabrielsantello/wholesale-and-retail-orders-dataset   Wholesale & Retail Orders Dataset                      3238262  2023-09-19 09:31:40.273000           4867         52                1
ankitbansal06/retail-orders                           Retail Orders                                           205161  2024-04-13 08:31:36.377000          30067         48       0.47058824
adarsh0806/influencer-merchandise-sales               Global Retail Sales Data: Orders, Reviews & Trends      125403  2024-12-10 14:07:52                  4083         38                1
abbas829/ecommerce-sales-dataset                      Ecommerce sales dataset                                 110951  2026-07-03 00:59:03.347000          14613        212                1
zusmani/pakistans-largest-ecommerce-dataset           Pakistan's Largest E-Commerce Dataset                 14432262  2021-01-19 11:42:57.930000          18740        400        0.9705882
heeraldedhia/groceries-dataset                        Groceries dataset                                       263057  2020-09-17 04:36:08.923000         103753        718                1
udaykumar025/retails-sales-analysis                   Retails Sales Analysis                                  364311  2026-09-10 15:17:46.960000           1971         23        0.9411765
minahilfatima12328/consumer-shopping-trends-analysis  Consumer Shopping Trends Analysis                       354898  2026-03-26 12:45:19.030000           3889         53                1
sumeakash/enhanced-superstore-sales-dataset           Enhanced Superstore Sales Dataset                      2814050  2026-05-31 16:32:51.343000           1247         29        0.9411765
divyjain28/superstore-sales                           Superstore Sales Analysis                              1579499  2026-05-15 08:16:38.500000           2444         39                1
mmumairkhattak/e-commerce-orders-dataset-2026-scra    E-commerce Orders Dataset 2026 | SCRA                  1796478  2026-06-11 06:56:56.550000           3920         56                1
shandeep777/retail-supply-chain-sales-dataset         Retail Supply Chain Sales Dataset                      1503953  2024-12-08 06:51:23.480000           8854         50        0.7058824
thuandao/superstore-sales-analytics                   SuperStore Sales Analytics                             2283450  2026-03-06 12:31:25.800000           6080         79                1
aditirai2607/super-market-dataset                     Super Market dataset                                   1577058  2024-11-26 14:04:03.960000           5213         45                1
wellkilo/supermarket-dataset                          Supermarket_Dataset                                    1168002  2025-04-25 12:28:25.210000           4281         52        0.8235294
abbas829/global-superstore-sales-dataset              Global Superstore Sales Dataset                        2814050  2026-05-23 00:41:54.710000           4050         45                1
nudratabbas/sql-practice-dataset-1-easy-queries       SQL Practice Dataset 1 (Easy) + Queries                  51567  2026-03-10 14:32:34.810000           4697         57                1
umerkk12/online-retail-business                       Online Retail Business                                 7571514  2021-01-20 03:42:36.527000           4370         47       0.64705884
sureshmecad/supplement-sales-prediction               Supplement Sales Prediction                            2317237  2021-09-17 08:09:33.293000           2722         39        0.9411765
ismatkhan121/supermarket-sales-dataset                Supermarket Sales Dataset                               503986  2026-01-20 14:24:10.177000           4429         41        0.8235294

In [8]:
!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
Downloading orders.csv.zip to C:\Users\Imraan\Documents\data_analytics_project

  0%|          | 0.00/200k [00:00<?, ?B/s]
100%|##########| 200k/200k [00:00<00:00, 814kB/s]
100%|##########| 200k/200k [00:00<00:00, 814kB/s]

In [9]:
import zipfile

with zipfile.ZipFile("orders.csv.zip", "r") as zip_ref:
    zip_ref.extractall(".")

In [10]:
import os

print(os.listdir())

['.git', '.gitignore', '.ipynb_checkpoints', 'orders.csv', 'orders.csv.zip', 'orders_data_analysis.ipynb']

In [11]:
import os
import shutil

os.makedirs("data", exist_ok=True)

shutil.move("orders.csv", "data/orders.csv")
shutil.move("orders.csv.zip", "data/orders.csv.zip")

print(os.listdir("data"))

['orders.csv', 'orders.csv.zip']

In [12]:
import pandas as pd
df = pd.read_csv("data/orders.csv")
print("Rows:", len(df))
print("Columns:", len(df.columns))

Rows: 9994
Columns: 16

In [13]:
df.head()

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order Id          9994 non-null   int64
 1   Order Date        9994 non-null   str
 2   Ship Mode         9993 non-null   str
 3   Segment           9994 non-null   str
 4   Country           9994 non-null   str
 5   City              9994 non-null   str
 6   State             9994 non-null   str
 7   Postal Code       9994 non-null   int64
 8   Region            9994 non-null   str
 9   Category          9994 non-null   str
 10  Sub Category      9994 non-null   str
 11  Product Id        9994 non-null   str
 12  cost price        9994 non-null   int64
 13  List Price        9994 non-null   int64
 14  Quantity          9994 non-null   int64
 15  Discount Percent  9994 non-null   int64
dtypes: int64(6), str(10)
memory usage: 1.2 MB

In [15]:
df.isnull().sum()

Order Id            0
Order Date          0
Ship Mode           1
Segment             0
Country             0
City                0
State               0
Postal Code         0
Region              0
Category            0
Sub Category        0
Product Id          0
cost price          0
List Price          0
Quantity            0
Discount Percent    0
dtype: int64

In [16]:
df.describe()

,Order Id,Postal Code,cost price,List Price,Quantity,Discount Percent
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,201.189714,229.756854,3.789574,3.484090
std,2885.163629,32063.693350,537.743203,623.245839,2.225110,1.114211
min,1.000000,1040.000000,0.000000,0.000000,1.000000,2.000000
25%,2499.250000,23223.000000,20.000000,20.000000,2.000000,2.000000
50%,4997.500000,56430.500000,50.000000,50.000000,3.000000,3.000000
75%,7495.750000,90008.000000,180.000000,210.000000,5.000000,4.000000
max,9994.000000,99301.000000,18110.000000,22640.000000,14.000000,5.000000

In [17]:
df.dtypes

Order Id            int64
Order Date            str
Ship Mode             str
Segment               str
Country               str
City                  str
State                 str
Postal Code         int64
Region                str
Category              str
Sub Category          str
Product Id            str
cost price          int64
List Price          int64
Quantity            int64
Discount Percent    int64
dtype: object